Enable JSON body-parser for the coverage middleware only
Globally using the `bodyParser.json()` for an application causes any requests
with content-length > 0 to break when using `ember server --proxy ...`, the
usual symptom being that GET and DELETE requests work, but POST and PUT
requests fail:

```
Error proxying to http://192.168.2.10:9900
socket hang up
Error: socket hang up
   at createHangUpError (_http_client.js:215:15)
   at Socket.socketCloseListener (_http_client.js:247:23)
   at Socket.emit (events.js:129:20)
   at TCP.close (net.js:476:12)
```

Restricting the body parser only to the path which the coverage middleware
handles resolves this problem.